### ISSUE TITLE
Annotations only working on Deployments, not StatefulSets or Pods

### ISSUE THREAD

**Issue by otherguy** [1Password/onepassword-operator#143]
The `operator.1password.io/item-path` annotation isn't working when attached to a `Pod` or a `StatefulSet`, only when attached to a `Deployment` object.

For external Helm charts (like for example https://artifacthub.io/packages/helm/bitnami/rabbitmq) it would be great if it were possible to use the 1Password annotation directly on a `Pod`.

**Comment by vquie** [comment]
Please also enable it on cronjobs. Why not enable it on all kinds of objects?

**Comment by vquie** [comment]
I created a helm chart to create secrets that can be used with other installations.
https://github.com/vquie/OnePasswordItem-helm

**Comment by edif2008** [comment]
Hey there.

Thank you for raising this with us.
It looks like this issue is related to #18. Therefore, I'd suggest you following that one for further updates.
