### ISSUE TITLE
Crazy number of logs produced!! 4000/min!!

### ISSUE THREAD

**Issue by tomjohnburton** [1Password/onepassword-operator#164]
### Your environment

Operator Version: 1.7.0

Connect Server Version: 1.7.0

Kubernetes Version: v1.26

## What happened?

I'm just looking at the logs of the onepassword containers and it's stream around 4000 logs per minute. Not sure if this is normal. 
Does it need to reconcile the secret so many times? Or is it reacting to an update?

## What did you expect to happen?

Fewer logs I guess?

<img width="1405" alt="Screenshot 2023-06-25 at 19 12 24" src="https://github.com/1Password/onepassword-operator/assets/39559415/e23bd5f5-4b7e-4a54-bea1-5c878e35618e">

**Comment by jillianwilson** [comment]
Hi there! I'm looking at moving some of these logs to only show up depending on the log level set. Are you able to share an example of your logs with any identifying information removed so that I can be sure i've addressed your issue?

**Comment by jillianwilson** [comment]
Closing this issue, but feel free to reopen with more details if the above MR didn't solve your issues.
