### ISSUE TITLE
Publish arm64 images

### ISSUE THREAD

**Issue by DWSR** [1Password/onepassword-operator#20]
For use with AWS Graviton instances and Raspberry Pis

I double checked and the project compiles and tests properly, so this should just be a matter of rigging up a pipeline to publish the image.

**Comment by DWSR** [comment]
Hi @jpcoenen,

This issue was prematurely closed. The `1password/connect-api` and `1password/connect-sync` images still don't have ARM64 variants.

**Comment by jpcoenen** [comment]
Hi Brandon :wave: 

I am sorry the confusion. I did not realize that there was no separate issue for the Connect images when linking the PR to the issue. A separate place for issues with Connect api and sync is in the making. Until that is ready, I'll re-open this issue as a reminder. 

Regarding the ARM images themselves: we are working on it.

**Comment by edif2008** [comment]
Heey @DWSR,

ARM images for both the API and the sync are available with Connect 1.5.0+.
Therefore, now both the operator and Connect should be supported on ARM.
I hope this solves your issue. Feel free to reopen it if you encounter any issues.
