### ISSUE TITLE
Multiple secrets in a deployment

### ISSUE THREAD

**Issue by franklouwers** [1Password/onepassword-operator#21]
Hi,

it looks like the current spec would not allow multiple secrets to be used by a single deployment?

how would you handle that case?

**Comment by florisvdg** [comment]
You can use the [`OnePasswordItem` CRD](https://github.com/1Password/onepassword-operator#usage) to add as manage secrets as you like. The deployment annotation is just a shorthand to quickly add a single secret to a deployment.

**Comment by nodesocket** [comment]
Is there a way to automatically take all secrets in a vault with a given tag and map them, vs having to explicitly define each secret in a CRD?

**Comment by florisvdg** [comment]
@nodesocket Not yet, but we're looking into such a solution.

**Comment by alexandrsemak** [comment]
Thank you for 1Passwort Connect integration, but I am also interesting in multiple secret references in Deployment annotation level.

**Comment by Nexus2k** [comment]
+1 it would be handy to just repeat the pod annotation multiple times to get multiple secrets added.
