### ISSUE TITLE
Support Annotations & Labels that are passed to the created secret

### ISSUE THREAD

**Issue by mcmarkj** [1Password/onepassword-operator#41]
### Summary
It'd be fantastic if I was able to set an annotation or Label on my OnePasswordItem object and this was passed into the Kubernetes secret that was created by the operator.  

### Use cases
A prime example of where this would be useful is [Jenkins credentials](https://jenkinsci.github.io/kubernetes-credentials-provider-plugin/examples/) that require several annotations for them to be ingested. 
Additionally, selectors can be used by kubectl to find certain secrets/objects. i.e. 
```
kubectl get secrets -l=app=frontend-secret
```

**Comment by TheCase** [comment]
Just ran into this exact problem myself.  Would be a very welcome feature.

**Comment by SimonBarendse** [comment]
Thanks for raising this @mcmarkj! This will be a great addition.

**Comment by mcmarkj** [comment]
I've opened https://github.com/1Password/onepassword-operator/pull/43 for this

**Comment by mcmarkj** [comment]
The code has been merged, so hopefully should go live in the next release 🤞
