### ISSUE TITLE
Websocket connection fail and not working auto-restart

### ISSUE THREAD

**Issue by iljun** [1Password/onepassword-operator#50]
### Your environment

Operator Version: latest

Connect Server Version: 1.1.0

Kubernetes Version: 1.18

## What happened?

onepassword connection pod causes the following websocket connection failure message
```
{"log_message":"(E) failed to connectEndpoint for discovered peer: failed to transport.CreateConnection: [transport-websocket] failed to Dial endpoint: dial tcp 10.60.15.232:8080: connect: connection refused","timestamp":"2021-07-05T09:17:22.508765459Z","level":1}
{"log_message":"(E) failed to connectEndpoint for discovered peer: failed to transport.CreateConnection: [transport-websocket] failed to Dial endpoint: dial tcp 10.60.15.232:8080: connect: connection refused","timestamp":"2021-07-05T09:17:22.508975963Z","level":1}
```

also, auto-restart annotation does not work.
I confirmed that the secret has changed through log, but the pod does not restart.
I have applied auto-restart annotation of deployment.

## What did you expect to happen?

1. I don't know what role the websocket, but there should be no failure log.
2. When secret is changed, it should be auto-restarted.

## Steps to reproduce

1. restart onepassword and openpassword-connect pod.
2. tailing onepassword pod log
3. update secret

**Comment by marcoteodoro** [comment]
Hi @iljun I have the same issue running Docker on a Linux server. Some settings work on localhost, but on the server, I encounter this error. Any idea what this could be?
