### ISSUE TITLE
Set owner reference in the K8s secret

### ISSUE THREAD

**Issue by OmerKahani** [1Password/onepassword-operator#51]
### Summary
One password Item CRD creates and manages a K8s secret; therefore, it can use the ownerReference API to describe this relationship. 

https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents

### Use cases
1. A user wants to know which onePasswordItem created the secret
2. ArgoCD can show the secrets as a child of the onePasswordItem
example from ArgoCD to how pods and RC are using ownerReference
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/8766193/125196107-31caa000-e261-11eb-902b-33f3bba4f4c3.png">
3. A user want to delete the onePasswordItem but keep the password (by using `--cascade=orphan`)

### Proposed solution
The one password operator should add ownerReference to the K8s secret spec.

### Is there a workaround to accomplish this today?
No

### References & Prior Work
https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents

**Comment by jillianwilson** [comment]
Hi there!

Thanks for the suggestion. We will look into potentially adding this feature in the future.

Cheers

**Comment by OmerKahani** [comment]
Hi,
Would you be open to getting a PR for that?
Is there any timeline for the next version?

Thanks!
