### ISSUE TITLE
Cannot use OnePasswordItem with terraform

### ISSUE THREAD

**Issue by villesau** [1Password/onepassword-operator#63]
### Your environment

Operator Version: latest at the time of writing

Connect Server Version: latest at the time of writing

Kubernetes Version:

## What happened?
Detailed description here: https://github.com/hashicorp/terraform/issues/29443

In a nutshell, something called "finalizers" appears in the OnePasswordItem which terraform tries to pull back and it cannot be ignored. This causes terraform to end up into limbo state which prevents using OnePasswordItems via terrafrom at all.

## What did you expect to happen?
Finalizers should maybe not appear in the OnePasswordItem after the item has been created?

## Steps to reproduce
See: https://github.com/hashicorp/terraform/issues/29443

E: Seems to be a problem with the provider, see https://github.com/hashicorp/terraform-provider-kubernetes/issues/1378

**Comment by SimonBarendse** [comment]
I agree, this seems to be a problem upstream in the Kubernetes Terraform provider. I'll close this issue in favor of https://github.com/hashicorp/terraform-provider-kubernetes/issues/1378, feel free to re-open if there's anything we should be doing.
