### ISSUE TITLE
v1.0.2 handles key names incorrectly

### ISSUE THREAD

**Issue by rembart** [1Password/onepassword-operator#65]
Hello

v1.0.2 handles keys incorrectly (eg. camelcase are converted to lower letters) - we see some failures related to this on our staging cluster which runs the latest op-operator tag. 

eg clientSecret -> clientsecret and breaks the oidc auth

**From your release notes:**
Titles and field names that include white space and other characters that are not a valid [DNS subdomain name](https://kubernetes.io/docs/concepts/configuration/secret/) will create Kubernetes secrets that have titles and fields in the following format:
 - Invalid characters before the first alphanumeric character and after the last alphanumeric character will be removed
 - All whitespaces between words will be replaced by `-`
 - All the letters will be lower-cased.

**From the kubernetes docs:**
The name of a Secret object must be a valid DNS subdomain name. [...]

The keys of data and stringData must consist of alphanumeric characters, -, _ or .. All key-value pairs in the stringData field are internally merged into the data field. If a key appears in both the data and the stringData field, the value specified in the stringData field takes precedence.

Rolling back to v1.0.1 and (!) recreate the crd for the secrets fixes the issue.

Best Klaus

**Comment by lemichello** [comment]
Having the same issue, too.
