### ISSUE TITLE
1password-operator does not support .envFrom

### ISSUE THREAD

**Issue by PLWagner** [1Password/onepassword-operator#73]
Hi,

I would like to use the `auto-restart` with secrets mounted on a Deployment object with the `envFrom:` argument instead of `env:`. But actually, only `env:` is supported:

https://github.com/1Password/onepassword-operator/blob/b574e394ad649d2cbf6f61192f00a1918cef8df3/pkg/onepassword/containers.go#L7

**Comment by samifruit514** [comment]
https://github.com/1Password/onepassword-operator/pull/74

**Comment by verkaufer** [comment]
Thank you for the PR, @samifruit514 ! We'll make sure this gets reviewed and get this into a future release.

**Comment by villesau** [comment]
@verkaufer out of curiosity, when will you make sure it gets into a future release?

**Comment by verkaufer** [comment]
@villesau I've re-raised this issue with one of my colleagues 👍  Can't give you an exact date but I'll keep an eye on this to make sure it doesn't fall through the cracks any further.

**Comment by villesau** [comment]
Thank you @verkaufer :) I think `.envFrom` is at least as popular method for picking up secrets if not even more popular than the other ways. All the projects I've been involved with have used `.envFrom` so far.
