### ISSUE TITLE
AUTO RESTART doesn't work

### ISSUE THREAD

**Issue by Fouz** [1Password/onepassword-operator#85]
### Your environment
Connect Api: 1.5.0
Kubernetes Version: v1.17.12

## What happened?
when creating a new item or updating an existing one the operator updates the operator doesn't restart any deployment that is using the secret. though I enabled `AUTO_RESTART` environemnt variable at the operator level.

## What did you expect to happen?
whenever I update items the deployments that are using the secret to be auto restarted

## Notes & Logs
the only log message I get when updating 1password item
```
{"level":"info","ts":1644144252.1661143,"logger":"update_op_kubernetes_secrets_task","msg":"Updating kubernetes secret 'xxxxx"}

```

**Comment by oojikoo** [comment]
same here

**Comment by OneideLuizSchneider** [comment]
same here, 
k8s version: 1.21
Connect api: 1.5.0

**Comment by OneideLuizSchneider** [comment]
Same here,

k8s version: 1.21
Connect api: 1.5.0

**Comment by oojikoo** [comment]
latest version seems to work!
try 
```
helm repo update
helm upgrade --install connect 1password/connect [PUT_OPTIONS_HERE]
```

**Comment by yalattas** [comment]
it does work with deployment. Yet, doesn't work with ArgoCD rollout
secret is injected into the pod correctly even with ArgoCD Rollout. But hot-reloading is not happening
